name: Terraform

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  DEV_PROJECT_ID: 'project-b1008fb7-e9d3-4eb5-81f'
  REGION: 'us-central1'
  DEV_WIF_PROVIDER: 'projects/717066773680/locations/global/workloadIdentityPools/testing/providers/test2'
  DEV_SERVICE_ACCOUNT: 'github-wif@project-b1008fb7-e9d3-4eb5-81f.iam.gserviceaccount.com'

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.DEV_WIF_PROVIDER }}
          service_account: ${{ env.DEV_SERVICE_ACCOUNT }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init & Plan
        run: |
          cd terraform/environments/qa
          terraform init
          terraform plan -out=tfplan -input=false

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: ${{ github.ref_name }}/tfplan

      - name: Terraform Apply
        run: |
          cd terraform/environments/qa
          terraform init
          terraform apply -input=false tfplan

          